name: DevopsKescefkoTestOrganization NodeJS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MONGO_URI: 'mongodb://superuser:${{ secrets.MONGO_PASSWORD }}@localhost:27017/superData'
      MONGO_USERNAME: 'superuser'
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

    services:
      mongo:
        image: siddharth67/mongo-db:non-prod
        ports:
          - 27017:27017

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup NodeJS Version - 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install Dependencies
      run: npm install

    - name: Unit Testing
      run: npm test --if-present

    - name: Run Coverage
      run: npm run coverage --if-present

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        version: 'latest'

    - name: Authenticate to Google Cloud
      env:
        GCP_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS_JSON }}
      run: echo "$GCP_CREDENTIALS_JSON" > "$HOME/gcloud-key.json" && gcloud auth activate-service-account --key-file="$HOME/gcloud-key.json"

    - name: Upload Coverage Report to GCS
      run: |
        # Assuming the coverage report is generated at 'coverage/coverage-final.json'
        gsutil cp coverage/coverage-final.json gs://${{ secrets.GCS_BUCKET_NAME }}/reports/coverage-final.json
