name: DevopsKescefkoTestOrganization NodeJS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MONGO_URI: 'mongodb://superuser:${{ secrets.MONGO_PASSWORD }}@localhost:27017/superData'
      MONGO_USERNAME: 'superuser'
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

    services:
      mongo:
        image: siddharth67/mongo-db:non-prod
        ports:
          - 27017:27017

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup NodeJS Version - 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install Dependencies
      run: npm install

    - name: Unit Testing
      run: npm test --if-present

    - name: Run Coverage
      run: npm run coverage --if-present

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'my-service-account@my-project.iam.gserviceaccount.com'

    - name: Upload Coverage Report to GCS
      uses: google-github-actions/upload-cloud-storage@v2
      with:
        path: coverage/coverage-final.json
        destination: '${{ secrets.GCS_BUCKET_NAME }}/reports/'
